# """
# Django settings for dadvar project.
#
# Generated by 'django-admin startproject' using Django 6.0.5.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/6.0/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/6.0/ref/settings/
# """
# import os
# from pathlib import Path
#
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
#
# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
#
# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-by-j7ch_*rhnyt7dkyxk8mr-srm*y62&_u)lp973ceve^9@9k0'
#
# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
#
# ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.dadvar.com']
# # و این رو هم اضافه کن (بعد از ALLOWED_HOSTS)
# USE_X_FORWARDED_HOST = True
# USE_X_FORWARDED_PORT = True
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
#
# # Application definition
#
# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'home.apps.HomeConfig',
#     'accounts.apps.AccountsConfig',
#     'django.contrib.sitemaps',  # برای sitemap.xml
#     'django.contrib.sites',  # برای canonical
# ]
#
# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     'django.middleware.gzip.GZipMiddleware'
# ]
#
# ROOT_URLCONF = 'dadvar.urls'
#
# TEMPLATES = [
#     {
#         'BACKEND' : 'django.template.backends.django.DjangoTemplates',
#         'DIRS' : [BASE_DIR / 'templates']
#         ,
#         'APP_DIRS' : True,
#         'OPTIONS' : {
#             'context_processors' : [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]
#
# WSGI_APPLICATION = 'dadvar.wsgi.application'
#
# # Database
# # https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# DATABASES = {
#     'default' : {
#         'ENGINE' : 'django.db.backends.sqlite3',
#         'NAME' : BASE_DIR / 'db.sqlite3',
#     }
# }
#
# # Password validation
# # https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
#
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME' : 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME' : 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME' : 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME' : 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]
#
# # Internationalization
# # https://docs.djangoproject.com/en/6.0/topics/i18n/
#
# LANGUAGE_CODE = 'en-us'
#
# TIME_ZONE = 'UTC'
#
# USE_I18N = True
#
# USE_TZ = True
#
# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/6.0/howto/static-files/
#
# STATIC_URL = 'static/'
# SITE_ID = 1
# ENVIRONMENT = os.getenv('DJANGO_ENV', 'development')  # development / production
# # ========== تنظیمات امنیتی بر اساس محیط ==========
# if ENVIRONMENT == 'production':
#     SECURE_SSL_REDIRECT = True
#     SESSION_COOKIE_SECURE = True
#     CSRF_COOKIE_SECURE = True
#     SECURE_HSTS_SECONDS = 31536000
#     # ... و بقیه تنظیمات امنیتی پروداکشن
# else:
#     # محیط توسعه
#     SECURE_SSL_REDIRECT = False
#     SESSION_COOKIE_SECURE = False
#     CSRF_COOKIE_SECURE = False
#     # سرور توسعه جنگو فقط HTTP
# # کش (برای سرعت و سئو)
# CACHES = {
#     'default' : {
#         'BACKEND' : 'django.core.cache.backends.locmem.LocMemCache',
#         'LOCATION' : 'unique-snowflake',
#     }
# }
#
# AUTH_USER_MODEL = 'accounts.User'
#
# # زرین‌پال
# ZARINPAL_MERCHANT_ID = 'xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx'  # از زرین‌پال بگیر
# ZARINPAL_SANDBOX = True  # در محیط تست، برای پروداکشن False کن

"""
Django settings for dadvar project.
Production-ready with .env support, Docker, and SEO optimization.
"""

import os
from pathlib import Path
from decouple import config  # pip install python-decouple
import dj_database_url  # pip install dj-database-url

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent

# ========== بارگذاری متغیرهای محیطی ==========
# اولویت با متغیرهای سیستمی است، سپس فایل .env
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default = False, cast = bool)
ENVIRONMENT = config('ENVIRONMENT', default = 'development')

# ========== تنظیمات هاست ==========
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# اصلاح CSRF_TRUSTED_ORIGINS - فقط برای هاست‌های معتبر
CSRF_TRUSTED_ORIGINS = []
for host in ALLOWED_HOSTS:
    host = host.strip()
    if host and host != '*':  # ستاره رو نادیده بگیر
        if not host.startswith('127.') and not host.startswith('localhost'):
            CSRF_TRUSTED_ORIGINS.append(f'https://{host}')
            CSRF_TRUSTED_ORIGINS.append(f'http://{host}')
CSRF_TRUSTED_ORIGINS.append('http://localhost')
CSRF_TRUSTED_ORIGINS.append('http://127.0.0.1')

# ========== پروکسی و SSL (برای Nginx) ==========
USE_X_FORWARDED_HOST = config('USE_X_FORWARDED_HOST', default = True, cast = bool)
USE_X_FORWARDED_PORT = config('USE_X_FORWARDED_PORT', default = True, cast = bool)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ========== برنامه‌های نصب شده ==========
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    # اپلیکیشن‌های خودمان
    'home.apps.HomeConfig',
    'accounts',
    'ckeditor',
    'ckeditor_uploader',
    # پکیج‌های جانبی (اختیاری - بعداً نصب کن)
    # 'django_cleanup.apps.CleanupConfig',  # حذف خودکار فایل‌های اضافی
    # 'robots',  # مدیریت robots.txt
    # 'django_celery_beat',  # تسک‌های زمانبندی شده
]

# ========== میدلورها ==========
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.gzip.GZipMiddleware',
]

# ========== URL و قالب‌ها ==========
ROOT_URLCONF = 'dadvar.urls'

TEMPLATES = [
    {
        'BACKEND' : 'django.template.backends.django.DjangoTemplates',
        'DIRS' : [BASE_DIR / 'templates'],
        'APP_DIRS' : True,
        'OPTIONS' : {
            'context_processors' : [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'dadvar.wsgi.application'

# ========== دیتابیس (با پشتیبانی از Docker و محیط‌های مختلف) ==========
if ENVIRONMENT == 'production' :
    # استفاده از PostgreSQL در پروداکشن (Docker)
    DATABASES = {
        'default' : {
            'ENGINE' : config('DB_ENGINE', default = 'django.db.backends.postgresql'),
            'NAME' : config('DB_NAME', default = 'dadvar_db'),
            'USER' : config('DB_USER', default = 'dadvar_user'),
            'PASSWORD' : config('DB_PASSWORD', default = ''),
            'HOST' : config('DB_HOST', default = 'postgres'),
            'PORT' : config('DB_PORT', default = '5432'),
            'CONN_MAX_AGE' : 60,
            'OPTIONS' : {
                'connect_timeout' : 10,
            }
        }
    }
else :
    # SQLite برای محیط توسعه (سریع و ساده)
    DATABASES = {
        'default' : {
            'ENGINE' : config('DEV_DB_ENGINE', default = 'django.db.backends.sqlite3'),
            'NAME' : config('DEV_DB_NAME', default = BASE_DIR / 'db.sqlite3'),
        }
    }

# ========== رمزنگاری ==========
AUTH_PASSWORD_VALIDATORS = [
    {'NAME' : 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME' : 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME' : 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME' : 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ========== بین‌المللی و زبان ==========
LANGUAGE_CODE = 'fa-ir'
TIME_ZONE = 'Asia/Tehran'
USE_I18N = True
USE_TZ = True

# ========== فایل‌های استاتیک و مدیا ==========
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ========== کش (Redis برای پروداکشن، LocMem برای توسعه) ==========
if ENVIRONMENT == 'production' and config('REDIS_URL', default = None) :
    CACHES = {
        'default' : {
            'BACKEND' : config('CACHE_BACKEND', default = 'django.core.cache.backends.redis.RedisCache'),
            'LOCATION' : config('REDIS_URL'),
            'OPTIONS' : {
                'CLIENT_CLASS' : 'django_redis.client.DefaultClient',
                'PARSER_CLASS' : 'redis.connection.HiredisParser',
                'CONNECTION_POOL_CLASS' : 'redis.BlockingConnectionPool',
                'CONNECTION_POOL_CLASS_KWARGS' : {
                    'max_connections' : 50,
                    'timeout' : 20,
                },
                'MAX_CONNECTIONS' : 100,
                'PICKLE_VERSION' : -1,
            },
            'KEY_PREFIX' : 'dadvar',
            'TIMEOUT' : 300,
        }
    }
else :
    CACHES = {
        'default' : {
            'BACKEND' : 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION' : 'dadvar-cache',
        }
    }

# ========== تنظیمات امنیتی (بر اساس محیط) ==========
if ENVIRONMENT == 'production' :
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default = True, cast = bool)
    SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default = True, cast = bool)
    CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default = True, cast = bool)
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default = 31536000, cast = int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default = True, cast = bool)
    SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default = True, cast = bool)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
else :
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0

# ========== سشن و لاگین ==========
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_COOKIE_HTTPONLY = True
SESSION_SAVE_EVERY_REQUEST = True

# ========== مدل کاربر سفارشی ==========
AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'home:index'
LOGOUT_REDIRECT_URL = 'home:index'

# ========== سایت و سئو ==========
SITE_ID = 1
SITE_NAME = config('SITE_NAME', default = 'دادور')
SITE_DOMAIN = config('SITE_DOMAIN', default = 'dadvar.ir')
SITE_URL = config('SITE_URL', default = 'https://dadvar.ir')

# متا تگ‌های پیش‌فرض
DEFAULT_META_TITLE = config('DEFAULT_META_TITLE', default = 'دادور | سامانه تخصصی وکلای ایران')
DEFAULT_META_DESCRIPTION = config('DEFAULT_META_DESCRIPTION', default = 'بهترین وکلای طلاق، مهریه، کیفری و حقوقی')

# ========== درگاه پرداخت زرین‌پال ==========
ZARINPAL_MERCHANT_ID = config('ZARINPAL_MERCHANT_ID', default = '')
ZARINPAL_SANDBOX = config('ZARINPAL_SANDBOX', default = True, cast = bool)
ZARINPAL_DESCRIPTION = config('ZARINPAL_DESCRIPTION', default = 'پرداخت اشتراک سامانه دادور')

# ========== ایمیل ==========
if ENVIRONMENT == 'production' :
    EMAIL_BACKEND = config('EMAIL_BACKEND', default = 'django.core.mail.backends.smtp.EmailBackend')
    EMAIL_HOST = config('EMAIL_HOST', default = 'smtp.gmail.com')
    EMAIL_PORT = config('EMAIL_PORT', default = 587, cast = int)
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', default = True, cast = bool)
    EMAIL_HOST_USER = config('EMAIL_HOST_USER', default = '')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default = '')
    DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default = 'noreply@dadvar.ir')
else :
    # در محیط توسعه، ایمیل در کنسول چاپ شود
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# ========== لاگ‌گیری ==========
LOGGING = {
    'version' : 1,
    'disable_existing_loggers' : False,
    'formatters' : {
        'verbose' : {
            'format' : '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style' : '{',
        },
        'simple' : {
            'format' : '{levelname} {asctime} {message}',
            'style' : '{',
        },
    },
    'handlers' : {
        'console' : {
            'class' : 'logging.StreamHandler',
            'formatter' : 'simple',
        },
        'file' : {
            'class' : 'logging.FileHandler',
            'filename' : BASE_DIR / 'logs/dadvar.log',
            'formatter' : 'verbose',
        },
    },
    'root' : {
        'handlers' : ['console'],
        'level' : config('LOG_LEVEL', default = 'INFO'),
    },
    'loggers' : {
        'django' : {
            'handlers' : ['file'],
            'level' : 'INFO',
            'propagate' : True,
        },
        'django.request' : {
            'handlers' : ['file'],
            'level' : 'WARNING',
            'propagate' : False,
        },
    },
}

# ایجاد پوشه لاگ اگر وجود نداشت
if not os.path.exists(BASE_DIR / 'logs') :
    os.makedirs(BASE_DIR / 'logs')

# ========== تنظیمات جنگو ۶ ==========
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240

# ========== تنظیمات امنیتی اضافی برای پروداکشن ==========
if ENVIRONMENT == 'production' :
    # هدرهای امنیتی
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # جلوگیری از Clickjacking
    X_FRAME_OPTIONS = 'DENY'

    # کاهش اطلاعات در هدرها
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# ========== تنظیمات آپلود فایل ==========
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB

# ========== تنظیمات سشن برای امنیت بیشتر ==========
if ENVIRONMENT == 'production' :
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = 'Lax'

# ========== برای اجرا در محیط داکر ==========
if os.environ.get('DOCKER_CONTAINER', False) :
    import socket
    import os

    hostname = socket.gethostname()
    if hostname :
        ALLOWED_HOSTS.append(hostname)

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 400,
        'width': '100%',
        'language': 'fa',
        'versionCheck': False,  # <--- این خط رو اضافه کن
        'extraPlugins': ','.join([
            'uploadimage',
            'image2',
        ]),
        'filebrowserUploadUrl': '/ckeditor/upload/',
        'filebrowserImageUploadUrl': '/ckeditor/upload/',
        'imageUploadUrl': '/ckeditor/upload/',
    },
    'simple': {
        'toolbar': 'Basic',
        'height': 200,
        'width': '100%',
        'language': 'fa',
        'versionCheck': False,  # <--- این خط رو اضافه کن
        'extraPlugins': ['uploadimage'],
    },
}
# استفاده از Redis Cache (برای پروداکشن)
# فعلاً برای توسعه از LocMem استفاده کن
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 3600,  # 1 ساعت
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# کش کردن صفحات استاتیک
CACHE_MIDDLEWARE_SECONDS = 3600
CACHE_MIDDLEWARE_KEY_PREFIX = 'vakiljo'