# Generated by Django 6.0.5 on 2026-05-15 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام طرح')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='مدت (روز)')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='اولویت نمایش')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='امکانات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'طرح اشتراک',
                'verbose_name_plural': 'طرح\u200cهای اشتراک',
                'ordering': ['-priority', 'price'],
            },
        ),
        migrations.CreateModel(
            name='LawyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=200, verbose_name='تخصص اصلی')),
                ('sub_speciality', models.CharField(blank=True, max_length=200, verbose_name='زیرتخصص')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField(verbose_name='توضیحات حرفه\u200cای')),
                ('profile_image', models.ImageField(blank=True, upload_to='lawyers/')),
                ('phone_display', models.CharField(blank=True, max_length=20)),
                ('bar_number', models.CharField(blank=True, max_length=50, verbose_name='شماره پروانه وکالت')),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0)),
                ('success_rate', models.PositiveSmallIntegerField(default=0, help_text='درصد موفقیت (۰ تا ۱۰۰)')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('faq_data', models.JSONField(blank=True, default=dict, help_text="مثلاً {'سوال':'پاسخ'}")),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('user', models.OneToOneField(limit_choices_to={'is_lawyer': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LawyerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه پرداخت')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='home.lawyerprofile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subscriptionplan')),
            ],
            options={
                'verbose_name': 'اشتراک وکیل',
                'verbose_name_plural': 'اشتراک\u200cهای وکلا',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='lawyerprofile',
            index=models.Index(fields=['city', 'speciality'], name='home_lawyer_city_781633_idx'),
        ),
        migrations.AddIndex(
            model_name='lawyerprofile',
            index=models.Index(fields=['slug'], name='home_lawyer_slug_f56715_idx'),
        ),
    ]
