# Generated by Django 6.0.5 on 2026-05-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=100, verbose_name='تخصص')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('h1_title', models.CharField(blank=True, max_length=100)),
                ('intro_text', models.TextField(blank=True, verbose_name='متن معرفی')),
                ('main_content', models.TextField(blank=True, verbose_name='محتوای اصلی')),
                ('tips_content', models.TextField(blank=True, verbose_name='راهنمای انتخاب')),
                ('faq_content', models.JSONField(blank=True, default=list, verbose_name='سوالات متداول')),
                ('avg_success_rate', models.PositiveSmallIntegerField(default=0, verbose_name='میانگین نرخ موفقیت')),
                ('total_lawyers', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد وکلا')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'محتوای صفحه لندینگ',
                'verbose_name_plural': 'محتوای صفحات لندینگ',
                'unique_together': {('speciality', 'city')},
            },
        ),
    ]
