# Generated by Django 6.0.5 on 2026-05-18 07:41

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_landingpagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpagecontent',
            name='intro_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='متن معرفی'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='main_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='محتوای اصلی'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='meta_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='meta_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='tips_content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='راهنمای انتخاب'),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات حرفه\u200cای'),
        ),
    ]
