# Generated by Django 6.0.5 on 2026-05-19 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_city_specialty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lawyerprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'پروفایل وکیل', 'verbose_name_plural': 'پروفایل\u200cهای وکلا'},
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='خلاصه\u200cای که در نتایج جستجو نمایش داده می\u200cشود (۱۵۰ کاراکتر)', null=True, verbose_name='خلاصه هوش مصنوعی'),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد امتیازدهندگان'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='توضیحات متا'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='عنوان متا'),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='years_of_experience',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='سال\u200cهای تجربه'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='lawyerprofile',
            index=models.Index(fields=['is_active'], name='home_lawyer_is_acti_71a41c_idx'),
        ),
    ]
